let subjects = [
  {
    name: "Harry Potter",
    alternate_names: [""],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    image: "http://hp-api.herokuapp.com/images/harry.jpg",
  },
  {
    name: "EE",
    alternate_names: [""],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    image: "http://hp-api.herokuapp.com/images/hermione.jpg",
  },
  {
    name: "انسترو",
    alternate_names: [""],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    image: "http://hp-api.herokuapp.com/images/hermione.jpg",
  },
  {
    name: "الكهرومغناطيسية",
    alternate_names: [""],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    image: "http://hp-api.herokuapp.com/images/hermione.jpg",
  },
  {
    name: "Anas Saeed",
    alternate_names: [""],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    image: "http://hp-api.herokuapp.com/images/hermione.jpg",
  },
  {
    name: "محمد لافي",
    alternate_names: [""],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    image: "http://hp-api.herokuapp.com/images/hermione.jpg",
  },
  {
    name: "EM2",
    alternate_names: [""],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    image: "http://hp-api.herokuapp.com/images/hermione.jpg",
  },
  {
    name: "EassadasdfE",
    alternate_names: [""],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    image: "http://hp-api.herokuapp.com/images/hermione.jpg",
  },
  {
    name: "EsssE",
    alternate_names: [""],
    species: "human",
    gender: "male",
    house: "Gryffindor",
    image: "http://hp-api.herokuapp.com/images/snape.jpg",
  },
];
